### ISSUE TITLE
iOS에서 앱 링크 찾는법

### ISSUE THREAD

**Issue by chokyungjin** [flutter-moum/flutter_open_appstore#12]
### 이 링크를 처음에 찾지 못해서 어려웠습니다!
---
![IMG_8744](https://user-images.githubusercontent.com/46750574/66853594-a011fe00-efba-11e9-915d-11dcfb396618.png)

*밑에 링크복사해서 URL 주소 복사하고 링크 확인!!*
---

**Comment by moonyoungCHAE** [comment]
또 다른 방법 ~~

iTunes 스토어 페이지로 이동합니다. 
앱을 검색하여 앱 페이지로 이동합니다. 
URL을 복사합니다. iTunes App Store URL은 다음 형식을 사용합니다.
http://itunes.apple.com/<country>/app/<app–name>/id<app-ID>?mt=8
