### ISSUE TITLE
Works well on Android Simulator but errors are printed in the console

### ISSUE THREAD

**Issue by aleaforny** [flutter-moum/flutter_open_appstore#20]
Hi fellows,

Just to let you know that I'm experiencing a non-critical issue with this fantastic plugin; while it's working perfectly under Android Simulator (I'm correctly redirected to the PlayStore), the following errors/warnings appear every time the function .redirect() is called :

`E/MethodChannel#flutter.moum.open_appstore(32282): Failed to handle method call
E/MethodChannel#flutter.moum.open_appstore(32282): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.moum.open_appstore(32282): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at flutter.moum.open_appstore.OpenAppstorePlugin.onMethodCall(OpenAppstorePlugin.java:38)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter.moum.open_appstore(32282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/DartMessenger(32282): Uncaught exception in binary message listener
E/DartMessenger(32282): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(32282): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/DartMessenger(32282): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:240)
E/DartMessenger(32282): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/DartMessenger(32282): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/DartMessenger(32282): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(32282): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/DartMessenger(32282): 	at android.os.Looper.loop(Looper.java:160)
E/DartMessenger(32282): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/DartMessenger(32282): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(32282): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger(32282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Just wanna make sure it's not that bad, perhaps it's only due to my configuration and it cannot be reproduced.

Cheers

**Comment by moonyoungCHAE** [comment]
Thank you for the report. :)

**Comment by aleaforny** [comment]
After upgrading Flutter to `v1.12.13+hotfix.5`, these warnings do not appear anymore. No idea what could have changed with this new Flutter version and this project.

**Comment by jumper423** [comment]
Same problem

```
E/MethodChannel#flutter.moum.open_appstore(15623): Failed to handle method call
E/MethodChannel#flutter.moum.open_appstore(15623): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.moum.open_appstore(15623): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:235)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at flutter.moum.open_appstore.OpenAppstorePlugin.onMethodCall(OpenAppstorePlugin.java:38)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter.moum.open_appstore(15623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
E/DartMessenger(15623): Uncaught exception in binary message listener
E/DartMessenger(15623): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(15623): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/DartMessenger(15623): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:250)
E/DartMessenger(15623): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(15623): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/DartMessenger(15623): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(15623): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/DartMessenger(15623): 	at android.os.Looper.loop(Looper.java:197)
E/DartMessenger(15623): 	at android.app.ActivityThread.main(ActivityThread.java:7814)
E/DartMessenger(15623): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(15623): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger(15623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
D/ViewRootImpl@c283e4f[MainActivity](15623): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(15623): prepareNavigationBarInfo() DecorView@a39ecd6[MainActivity]
D/InputMethodManager(15623): getNavigationBarColor() -855310
D/InputTransport(15623): Input channel destroyed: 'ClientS', fd=88

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale ru_RU.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
